version: '3'

services:
  nats-server:
    image: nats:latest
  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservicios-nestjs-455721/nest-registry/client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  auth-micro-service:
    build: 
      context: ./auth-micro-service
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservicios-nestjs-455721/nest-registry/auth-micro-service-prod
    ports:
      - ${AUTH_MS_PORT}:${AUTH_MS_PORT}
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-micro-service:
    build:
      context: ./products-micro-service
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservicios-nestjs-455721/nest-registry/products-micro-service-prod
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
  
  orders-micro-service:
    build:
      context: ./orders-micro-service
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: northamerica-south1-docker.pkg.dev/microservicios-nestjs-455721/nest-registry/orders-micro-service-prod
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  payments-micro-service:
    build: 
      context: ./payments-micro-service
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservicios-nestjs-455721/nest-registry/payments-micro-service-prod
    ports:
      - ${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}
    environment:
      - PORT=${PAYMENT_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET= ${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL},
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL},
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}