version: '3'

services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
  
  products-micro-service:
    build: ./products-micro-service
    ports:
      - "3001:3001"
    volumes:
      - ./products-micro-service/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
  
  orders-micro-service:
    depends_on:
      - orders-db
    build: ./orders-micro-service
    ports:
      - "3002:3002"
    volumes:
      - ./orders-micro-service/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public

  orders-db:
    container_name: orders-database
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-micro-service/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ordersdb

  payments-micro-service:
    build: ./payments-micro-service
    volumes:
      - ./payments-micro-service/src:/usr/src/app/src
    command: npm run start:dev
    ports:
      - ${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}
    environment:
      - PORT=${PAYMENT_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET= ${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL},
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL},
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
