apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-micro-service-prod
  name: auth-micro-service-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-micro-service-prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-micro-service-prod
    spec:
      containers:
      - image: northamerica-south1-docker.pkg.dev/microservicios-nestjs-455721/nest-registry/auth-micro-service-prod
        name: auth-micro-service-prod
        env:
        - name: PORT
          value: "3004"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: database_url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt_secret
        resources: {}
status: {}
